=== juliaf20/LND2018-1/Practicas/A17/Ejemplos/biblio.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="0.1" xml:lang="es">
    <xs:element name="biblioteca">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="libro" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name = "codigo" type="xs:integer"/>
                            
                            <xs:element name = "titulo" type="xs:string"/>
                            
                            <xs:element name = "Editorial" type="xs:string"/>
                            
                            <xs:element name = "Edicion" type="xs:string"/>
                            <xs:element name = "ISBN" type="xs:string"/>
                            <xs:element name = "Numero_de_paginas" type="xs:integer"/>
                            <xs:element name = "Autor" type="xs:string"/>
                            
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== juliaf20/LND2018-1/Practicas/A17/Ejemplos/biblio.xml
<?xml version="1.0" encoding ="ISO-8859-1"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="biblio.xsd">
    
    <libro>
        <codigo>
            001
        </codigo>
        <titulo>
            El Oscuro PAsajero
        </titulo>
        <Editorial>
            Umbriel
        </Editorial>
        <Edicion>
            La primera
        </Edicion>
        <ISBN>
            84-95618-83-4
        </ISBN>
        <Numero_de_paginas>
            251
        </Numero_de_paginas>
        <Autor>
            Jeff Lindsay
        </Autor>
    </libro>
</biblioteca>
